# configuration for https://cargo-generate.github.io/cargo-generate/

[template]
cargo_generate_version = ">=0.20.0"
sub_templates = ["cli-template", "component-template", "dumbpipe-template", "gnostr-component-template", "lib-template", "lib-term-template", "simple-async-template", "simple-template", "user-input-template"]
